<a href="https://colab.research.google.com/github/IgneshSamal/Multiple-Disease-Prediction/blob/main/Multiple_disease_prediction_system_diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    recall_score,
    precision_score,
    f1_score,
    confusion_matrix
)

Data Collection and Analysis

PIMA Diabetes Dataset

In [2]:
# loading the diabetes dataset to a pandas DataFrame
diabetes_dataset = pd.read_csv('/content/diabetes.csv')

In [3]:
# printing the first 5 rows of the dataset
diabetes_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
# number of rows and Columns in this dataset
diabetes_dataset.shape

(768, 9)

In [5]:
# getting the statistical measures of the data
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

0 --> Non-Diabetic

1 --> Diabetic

In [7]:
diabetes_dataset.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [8]:
# separating the data and labels
X = diabetes_dataset.drop(columns = 'Outcome', axis=1)
Y = diabetes_dataset['Outcome']

In [9]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [10]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Train Test Split

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

In [12]:
print(X.shape, X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)

In [13]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Model Selection

In [14]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "SVC": SVC(kernel='linear'),
    "KNN": KNeighborsClassifier(n_neighbors=5)
}

results = {}

for name, model in models.items():

    # Train model
    model.fit(X_train_scaled, Y_train)

    # Predict test data
    y_pred = model.predict(X_test_scaled)

    # Calculate metrics
    accuracy = accuracy_score(Y_test, y_pred)
    recall = recall_score(Y_test, y_pred)
    precision = precision_score(Y_test, y_pred)
    f1 = f1_score(Y_test, y_pred)

    results[name] = {
        "model": model,
        "accuracy": accuracy,
        "recall": recall,
        "precision": precision,
        "f1": f1
    }

    print(f"\n{name}")
    print("-------------------------")
    print(f"Accuracy  : {accuracy:.4f}")
    print(f"Recall    : {recall:.4f}")
    print(f"Precision : {precision:.4f}")
    print(f"F1 Score  : {f1:.4f}")

Logistic Regression
-------------------------
Accuracy  : 0.7597
Recall    : 0.5185
Precision : 0.7179
F1 Score  : 0.6022

SVC
-------------------------
Accuracy  : 0.7727
Recall    : 0.5185
Precision : 0.7568
F1 Score  : 0.6154

KNN
-------------------------
Accuracy  : 0.7143
Recall    : 0.4259
Precision : 0.6389
F1 Score  : 0.5111

In [15]:
best_name = None

for name, metrics in results.items():

    if best_name is None:
        best_name = name
        continue

    current = results[name]
    best = results[best_name]

    recall_difference = abs(
        current["recall"] - best["recall"]
    )

    # If recalls are almost identical
    if recall_difference < 0.01:

        # Second priority: F1-score
        if current["f1"] > best["f1"]:
            best_name = name

        # Third priority: Precision
        elif (
            current["f1"] == best["f1"]
            and current["precision"] > best["precision"]
        ):
            best_name = name

    # Otherwise, choose higher recall
    elif current["recall"] > best["recall"]:
        best_name = name


best_model = results[best_name]["model"]

print("\n================================")
print("BEST MODEL:", best_name)
print("================================")
print("Recall    :", results[best_name]["recall"])
print("F1 Score  :", results[best_name]["f1"])
print("Precision :", results[best_name]["precision"])
print("Accuracy  :", results[best_name]["accuracy"])

================================
BEST MODEL: SVC
================================
Recall    : 0.5185185185185185
F1 Score  : 0.6153846153846154
Precision : 0.7567567567567568
Accuracy  : 0.7727272727272727

Model Evaluation

In [16]:
best_prediction = best_model.predict(X_test_scaled)

cm = confusion_matrix(Y_test, best_prediction)

print("\nConfusion Matrix:")
print(cm)

TN, FP, FN, TP = cm.ravel()

print("\nTrue Negative :", TN)
print("False Positive:", FP)
print("False Negative:", FN)
print("True Positive :", TP)

Confusion Matrix:
[[91  9]
 [26 28]]

True Negative : 91
False Positive: 9
False Negative: 26
True Positive : 28

Training-Test Accuracy

In [17]:
X_train_prediction = best_model.predict(X_train_scaled)

training_data_accuracy = accuracy_score(
    Y_train,
    X_train_prediction
)

X_test_prediction = best_model.predict(X_test_scaled)

test_data_accuracy = accuracy_score(
    Y_test,
    X_test_prediction
)

print("Training Accuracy:", training_data_accuracy)
print("Test Accuracy:", test_data_accuracy)

Training Accuracy: 0.7866449511400652
Test Accuracy: 0.7727272727272727

Making a Predictive System

In [18]:
input_data = (5,166,72,19,175,25.8,0.587,51)

# Convert input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# Reshape
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)

# Scale using the SAME scaler used during training
input_data_scaled = scaler.transform(input_data_reshaped)

# Predict using the selected best model
prediction = best_model.predict(input_data_scaled)

print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

[1]
The person is diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

Saving the trained model

In [19]:
import pickle

filename = 'parkinsons_model.sav'

model_data = {
    'model': best_model,
    'scaler': scaler
}

pickle.dump(model_data, open(filename, 'wb'))

print("Best model and scaler saved successfully!")

Best model and scaler saved successfully!

In [20]:
#loading the saved model
loaded_data = pickle.load(
    open('parkinsons_model.sav', 'rb')
)

loaded_model = loaded_data['model']
loaded_scaler = loaded_data['scaler']

In [21]:
print("Loaded model:", loaded_model)
print("Loaded scaler:", loaded_scaler)

Loaded model: SVC(kernel='linear')
Loaded scaler: StandardScaler()

In [22]:
for column in X.columns:
  print(column)

Pregnancies
Glucose
BloodPressure
SkinThickness
Insulin
BMI
DiabetesPedigreeFunction
Age